{
 "title": "Evidently - Dashboard",
 "time": { "from": "2022-01-31T18:30:00.000Z", "to": "2022-02-08T18:29:59.000Z" },
 "panels": [
  {
   "title": "Share Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Num_Drifted_Colums",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction_Drift",
   "type": "timeseries",
   "description": "Prediction_Drift",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}